// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObligatorioDDA2.MinijuegosAPI.Data;

#nullable disable

namespace ObligatorioDDA2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112124522_cambiosModelo")]
    partial class cambiosModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioDDA2.MinijuegosAPI.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("codigo_pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo_proposicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("numeros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proposicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("respuestaMatematica")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("secuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
